apiVersion: v1
kind: Service
metadata:
  name: mobile-wallet-fraud-service
spec:
  type: LoadBalancer
  selector:
    app: mobile-wallet-fraud-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501